### ISSUE TITLE
Call to undefined method ManageAds_Controller

### ISSUE THREAD

**Issue by ghost** [Spuds/Elk-Simple-Ads#1]
Hello dear developers,
I want to use this plugin, but this error message appears when you add an ad in the back end.

```
Fatal error: Call to undefined method ManageAds_Controller :: _ check errors () in on line 272 /www/htdocs/xxxxxxxxx/elkarteforum.wpzweinull.ch/sources/admin/ManageAds.controller.php
```

Can you tell me there might help to resolve the error? Thank you in advance.

I have PHP 5.5 and the latest version of MySQL and use ElkArte 1.0.4.

**Comment by Spuds** [comment]
I'll take a look at this in the AM and post a fix.  Thanks for the report.

**Comment by Spuds** [comment]
Should be fixed now, get the latest here: https://github.com/Spuds/Elk-Simple-Ads/releases/tag/1.0.2
