### ISSUE TITLE
You left the name field empty - ElkArte 1.0.4

### ISSUE THREAD

**Issue by ghost** [Spuds/Elk-Simple-Ads#2]
Hello dear developers,
I have just installed the latest plug-in version, but when I create an ad, this error message appears.

```
You left the name field empty.
```

I wanted to use Google Adsense and have entered the name of the ad in the Name box and then simply inserted the Adsense code. Am I doing this wrong?

Would be good if you could help me. Thank you in advance.

**Comment by Spuds** [comment]
That should now be fixed here:  https://github.com/Spuds/Elk-Simple-Ads/releases/download/1.0.2/elk_SimpleAds.zip

Uninstall the current version, download the new one and re-install.

**Comment by ghost** [comment]
Thank you, has just everything works and everything is working. The ads appear :)
