### ISSUE TITLE
ads not showing

### ISSUE THREAD

**Issue by anagnam** [Spuds/Elk-Simple-Ads#3]
I'm using ElkArte 1.0.5 and I installed the addons without issues. I created the add in the right positions but its not showing in the forum. Any idea why?

**Comment by Spuds** [comment]
No sure, so I'll start with the basics.  Make sure you have:
- Activated the Ad.  Active ones have a check mark as the first icon under the actions column in the Ad List.  If you instead have a red circle, then its not active and you need to click that red icon to activate it.
- You have the Ad enabled for the area of the site you are viewing.  When you created (or edit)   you will see an Actions area.  This define in which areas the Ad will be seen.
- You are in a membergroup that can see ads.  When creating / editing there is a membergroup section.  So for example if are an admin and you want to see ads, then you need to select administrators in that member list.

**Comment by anagnam** [comment]
many thanks @Spuds . its working now ;-)
